### ISSUE TITLE
Suppress scapy IPv6 warning

### ISSUE THREAD

**Issue by a110605** [portantier/habu#1]
Hi,
This is a interesting project using "Scapy-Python3" to build networking tools.

I suggest to suppress the WARNING caused by scapy.

`WARNING: No route found for IPv6 destination :: (no default route?) `

AndyLee

**Comment by fportantier** [comment]
Yes, you're right. I promise that I will remove the warning for the next revision.

Regards,

**Comment by fportantier** [comment]
Removed in all (or almost all) commands
