### ISSUE TITLE
shodan api

### ISSUE THREAD

**Issue by jepunband** [portantier/habu#21]
**Describe the bug**
shodan api key config file to update>?

**To Reproduce**
habu.shodan.open

**Expected behavior**
to show the scanned results.

**Environment**
 - OS: kali

**Comment by fportantier** [comment]
Hi, you can save your shodan api key editing the file "~/.habu.json", or, using the command config.set, like this:

habu.config.set SHODAN_APIKEY YOUR_SHODAN_API_KEY

You can use the following command:

habu.config.show --show-keys

To check that the config has been saved correctly.
