### ISSUE TITLE
Switch to Scapy v2.4.0?

### ISSUE THREAD

**Issue by guedou** [portantier/habu#3]
I noticed that your are using an outdate Scapy fork diverged, that does not follow evolutions and fixes from https://github.com/secdev/scapy

You should consider switching to scapy in you requirements.txt

**Comment by fportantier** [comment]
Hi! Good comment. 

My only reason to no change the requirements is that Kali Linux python3-scapy is for scapy3k, and python-scapy is for python2. So, there is not a Kali Linux package for the project version that you've commented. Right?

**Comment by guedou** [comment]
Don’t know for jail kali but it is currently pushed to distros.

I noticed that you are using pip, that is why I sent a friendly reminder =)

**Comment by fportantier** [comment]
Done! We migrated the code to Scapy official.  :)

**Comment by guedou** [comment]
Awesome!
