### ISSUE TITLE
error when try to install habu

### ISSUE THREAD

**Issue by brahmanggi** [portantier/habu#4]
I've got these comment below when trying to install habu using sudo pip3 install habu :

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-2s2bcpwn/pycrypto/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-eq7sy789-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-2s2bcpwn/pycrypto/

**Comment by fportantier** [comment]
I'm installing without errors.

The error that you've pasted it's related with the compilation of pycrypto.

Maybe, you need to install the pycrypto dependency packages. At lease, install build-essential.

What Linux distro do you use?

**Comment by brahmanggi** [comment]
I've change the linux distro to manjaro and its runs

thank you
